atriumvisionblog_configuration:
  path: /atriumvisionblog/configure
  methods: [GET, POST]
  defaults:
    _controller: 'PrestaShop\Module\AtriumVisionBlog\Controller\AdminBlogConfigurationController::indexAction'
    # Needed to work with tab system
    _legacy_controller: 'AdminBlogConfiguration'
    _legacy_link: 'AdminBlogConfiguration'
